# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'furby-translator' do

pod 'HNKServerFacade', '~> 0.2'
pod 'Mantle', '~> 1.0'

end

target 'furby-translatorTests' do

end

